# Generated by Django 5.2.5 on 2025-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_category_slug_product_slug_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_sum',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
